[all:vars]
ansible_network_os=cisco.fmcansible.fmc

[vfmc]
<IP ADDRESS> ansible_user=ansible ansible_password=<Enter your password> ansible_httpapi_port=443 ansible_httpapi_use_ssl=True ansible_httpapi_validate_certs=False

[vfmc:vars]
network_type=HOST
